stages:
  - deploy-dev
  - deploy-prod

deploy-dev:
  stage: deploy-dev
  image: 9350733512/ansible:0.0.2

  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOYER_PRIVATE_KEY" >> ~/.ssh/id_ed25519
    - cat ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ls
    - pwd
    - echo 'hello'

  script:
    - cd ansible && ansible-playbook -i inventory/server-dev.ini deploy.yml --become --become-method=sudo